package
{
   import flash.display.Sprite;
   import lang.UILang;
   import manager.DataManager;
   import mx.binding.FunctionReturnWatcher;
   import mx.binding.IWatcherSetupUtil;
   import mx.binding.PropertyWatcher;
   import mx.binding.StaticPropertyWatcher;
   import mx.core.IFlexModuleFactory;
   import ui.beast.BeastPanel;
   
   public class _ui_beast_BeastPanelWatcherSetupUtil extends Sprite implements IWatcherSetupUtil
   {
      
      public function _ui_beast_BeastPanelWatcherSetupUtil()
      {
         super();
      }
      
      public static function init(param1:IFlexModuleFactory) : void
      {
         BeastPanel.watcherSetupUtil = new _ui_beast_BeastPanelWatcherSetupUtil();
      }
      
      public function setup(param1:Object, param2:Function, param3:Array, param4:Array) : void
      {
         var target:Object = param1;
         var propertyGetter:Function = param2;
         var bindings:Array = param3;
         var watchers:Array = param4;
         watchers[80] = new StaticPropertyWatcher("FeedItem1",{"propertyChange":true},[bindings[117]],null);
         watchers[95] = new PropertyWatcher("rewardExp",{"propertyChange":true},[bindings[132]],propertyGetter);
         watchers[58] = new PropertyWatcher("myBeast",{"propertyChange":true},[bindings[68]],propertyGetter);
         watchers[115] = new StaticPropertyWatcher("BeastComposeInfo",{"propertyChange":true},[bindings[158]],null);
         watchers[103] = new PropertyWatcher("newBeast",{"propertyChange":true},[bindings[149],bindings[148],bindings[146],bindings[156],bindings[147],bindings[145]],propertyGetter);
         watchers[107] = new PropertyWatcher("level",{"propertyChange":true},[bindings[148]],null);
         watchers[106] = new PropertyWatcher("name",{"propertyChange":true},[bindings[147]],null);
         watchers[105] = new PropertyWatcher("id",{"propertyChange":true},[bindings[149],bindings[146],bindings[156]],null);
         watchers[104] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[145]],null);
         watchers[97] = new PropertyWatcher("smallLandList",{"propertyChange":true},[bindings[134]],propertyGetter);
         watchers[99] = new PropertyWatcher("visitLand2",{"propertyChange":true},[bindings[136]],propertyGetter);
         watchers[16] = new StaticPropertyWatcher("ReBirthTip3",{"propertyChange":true},[bindings[28]],null);
         watchers[21] = new StaticPropertyWatcher("BirthTip3",{"propertyChange":true},[bindings[32]],null);
         watchers[37] = new StaticPropertyWatcher("BeastInfo",{"propertyChange":true},[bindings[47]],null);
         watchers[43] = new StaticPropertyWatcher("BeastTip",{"propertyChange":true},[bindings[53]],null);
         watchers[7] = new StaticPropertyWatcher("Rest",{"propertyChange":true},[bindings[141],bindings[11]],null);
         watchers[98] = new PropertyWatcher("visitLand1",{"propertyChange":true},[bindings[135]],propertyGetter);
         watchers[81] = new PropertyWatcher("feedItem2",{"propertyChange":true},[bindings[119]],propertyGetter);
         watchers[36] = new StaticPropertyWatcher("BeastTrainTip4",{"propertyChange":true},[bindings[46]],null);
         watchers[0] = new StaticPropertyWatcher("Beast",{"propertyChange":true},[bindings[0]],null);
         watchers[55] = new StaticPropertyWatcher("Instance",null,[bindings[66]],null);
         watchers[56] = new PropertyWatcher("parcel",{"propertyChange":true},[bindings[66]],null);
         watchers[57] = new PropertyWatcher("feedAll",{"propertyChange":true},[bindings[66]],null);
         watchers[59] = new StaticPropertyWatcher("ChooseBeast",{"propertyChange":true},[bindings[69]],null);
         watchers[101] = new StaticPropertyWatcher("BeastCompose",{"propertyChange":true},[bindings[143]],null);
         watchers[66] = new PropertyWatcher("growStrength",{"propertyChange":true},[bindings[90],bindings[89]],propertyGetter);
         watchers[10] = new StaticPropertyWatcher("BirthTip2",{"propertyChange":true},[bindings[14]],null);
         watchers[26] = new PropertyWatcher("feedItem",{"propertyChange":true},[bindings[41],bindings[39]],propertyGetter);
         watchers[28] = new PropertyWatcher("id",{"propertyChange":true},[bindings[41]],null);
         watchers[88] = new StaticPropertyWatcher("Silver",{"propertyChange":true},[bindings[128]],null);
         watchers[33] = new StaticPropertyWatcher("BeastTrain",{"propertyChange":true},[bindings[45]],null);
         watchers[116] = new StaticPropertyWatcher("BeastComposeDesc",{"propertyChange":true},[bindings[159]],null);
         watchers[109] = new PropertyWatcher("oldBeast",{"propertyChange":true},[bindings[151],bindings[156],bindings[154],bindings[152],bindings[155],bindings[153]],propertyGetter);
         watchers[113] = new PropertyWatcher("level",{"propertyChange":true},[bindings[154]],null);
         watchers[111] = new PropertyWatcher("name",{"propertyChange":true},[bindings[152]],null);
         watchers[112] = new PropertyWatcher("id",{"propertyChange":true},[bindings[156],bindings[155],bindings[153]],null);
         watchers[110] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[151]],null);
         watchers[92] = new StaticPropertyWatcher("Gold",{"propertyChange":true},[bindings[131]],null);
         watchers[69] = new PropertyWatcher("growStamina",{"propertyChange":true},[bindings[96],bindings[95]],propertyGetter);
         watchers[91] = new PropertyWatcher("todayTime",{"propertyChange":true},[bindings[130]],propertyGetter);
         watchers[53] = new PropertyWatcher("isItemOpen",{"propertyChange":true},[bindings[64]],propertyGetter);
         watchers[71] = new StaticPropertyWatcher("Full",{"propertyChange":true},[bindings[105],bindings[107],bindings[99],bindings[103],bindings[101]],null);
         watchers[89] = new StaticPropertyWatcher("Consume",{"propertyChange":true},[bindings[129]],null);
         watchers[102] = new StaticPropertyWatcher("BeastComposeDrag",{"propertyChange":true},[bindings[144]],null);
         watchers[29] = new PropertyWatcher("likeShow",{"propertyChange":true},[bindings[42]],propertyGetter);
         watchers[108] = new StaticPropertyWatcher("BeastComposeDrag2",{"propertyChange":true},[bindings[150]],null);
         watchers[31] = new PropertyWatcher("tipArr",{"propertyChange":true},[bindings[44]],propertyGetter);
         watchers[32] = new FunctionReturnWatcher("getItemAt",target,function():Array
         {
            return [target.type - 1];
         },{"collectionChange":true},[bindings[44]],null);
         watchers[27] = new StaticPropertyWatcher("Feed",{"propertyChange":true},[bindings[40],bindings[121],bindings[118]],null);
         watchers[6] = new PropertyWatcher("beastList",{"propertyChange":true},[bindings[140],bindings[10]],propertyGetter);
         watchers[9] = new StaticPropertyWatcher("Birth",{"propertyChange":true},[bindings[13]],null);
         watchers[68] = new PropertyWatcher("growAgility",{"propertyChange":true},[bindings[94],bindings[93]],propertyGetter);
         watchers[93] = new StaticPropertyWatcher("BeastExp",{"propertyChange":true},[bindings[132]],null);
         watchers[34] = new PropertyWatcher("trainMaxTime",{"propertyChange":true},[bindings[45]],propertyGetter);
         watchers[35] = new PropertyWatcher("trainTodayTime",{"propertyChange":true},[bindings[45]],propertyGetter);
         watchers[79] = new PropertyWatcher("feedItem1",{"propertyChange":true},[bindings[116]],propertyGetter);
         watchers[87] = new PropertyWatcher("copperCost",{"propertyChange":true},[bindings[127]],propertyGetter);
         watchers[1] = new PropertyWatcher("currentIndex",{"propertyChange":true},[bindings[124],bindings[82],bindings[8],bindings[67],bindings[1],bindings[3],bindings[7],bindings[5],bindings[138]],propertyGetter);
         watchers[5] = new StaticPropertyWatcher("MyBeast",{"propertyChange":true},[bindings[9],bindings[139]],null);
         watchers[2] = new StaticPropertyWatcher("AdventureArea",{"propertyChange":true},[bindings[2]],null);
         watchers[30] = new PropertyWatcher("type",{"propertyChange":true},[bindings[43],bindings[44]],propertyGetter);
         watchers[11] = new PropertyWatcher("selectBeast",{"propertyChange":true},[bindings[15],bindings[62],bindings[79],bindings[31],bindings[16],bindings[48],bindings[123],bindings[112],bindings[80],bindings[113],bindings[86],bindings[59],bindings[34],bindings[73],bindings[70],bindings[85],bindings[60],bindings[61],bindings[106],bindings[29],bindings[122],bindings[100],bindings[83],bindings[58],bindings[75],bindings[18],bindings[63],bindings[81],bindings[27],bindings[17],bindings[77],bindings[38],bindings[28],bindings[102],bindings[84],bindings[57],bindings[37],bindings[51],bindings[23],bindings[104],bindings[87],bindings[72],bindings[35],bindings[49],bindings[54],bindings[71],bindings[22],bindings[33],bindings[21],bindings[78],bindings[52],bindings[24],bindings[88],bindings[111],bindings[36],bindings[19],bindings[114],bindings[26],bindings[55],bindings[50],bindings[108],bindings[76],bindings[109],bindings[74],bindings[20],bindings[110],bindings[25],bindings[56]],propertyGetter);
         watchers[13] = new PropertyWatcher("level",{"propertyChange":true},[bindings[36],bindings[72],bindings[31],bindings[16]],null);
         watchers[47] = new PropertyWatcher("physicalDefence",{"propertyChange":true},[bindings[57],bindings[76]],null);
         watchers[39] = new PropertyWatcher("skill2",{"propertyChange":true},[bindings[49]],null);
         watchers[52] = new PropertyWatcher("speed",{"propertyChange":true},[bindings[62],bindings[81]],null);
         watchers[75] = new PropertyWatcher("totalGrowStamina",{"propertyChange":true},[bindings[106]],null);
         watchers[49] = new PropertyWatcher("spellDefence",{"propertyChange":true},[bindings[78],bindings[59]],null);
         watchers[64] = new PropertyWatcher("stamina",{"propertyChange":true},[bindings[87],bindings[106]],null);
         watchers[25] = new PropertyWatcher("maxExp",{"propertyChange":true},[bindings[73],bindings[38],bindings[37]],null);
         watchers[38] = new PropertyWatcher("skill1",{"propertyChange":true},[bindings[48]],null);
         watchers[73] = new PropertyWatcher("totalGrowIntelligence",{"propertyChange":true},[bindings[102]],null);
         watchers[24] = new PropertyWatcher("nowExp",{"propertyChange":true},[bindings[73],bindings[38],bindings[37]],null);
         watchers[14] = new PropertyWatcher("bigHead",{"propertyChange":true},[bindings[17]],null);
         watchers[63] = new PropertyWatcher("agility",{"propertyChange":true},[bindings[104],bindings[86]],null);
         watchers[72] = new PropertyWatcher("totalGrowStrength",{"propertyChange":true},[bindings[100]],null);
         watchers[74] = new PropertyWatcher("totalGrowAgility",{"propertyChange":true},[bindings[104]],null);
         watchers[62] = new PropertyWatcher("intelligence",{"propertyChange":true},[bindings[102],bindings[85]],null);
         watchers[83] = new PropertyWatcher("nowTotalAbility",{"propertyChange":true},[bindings[122],bindings[123]],null);
         watchers[46] = new PropertyWatcher("physicalAttack",{"propertyChange":true},[bindings[75],bindings[56]],null);
         watchers[23] = new PropertyWatcher("name",{"propertyChange":true},[bindings[35],bindings[71]],null);
         watchers[44] = new PropertyWatcher("jobName",{"propertyChange":true},[bindings[54]],null);
         watchers[15] = new PropertyWatcher("rebirth",{"propertyChange":true},[bindings[19],bindings[23],bindings[26],bindings[31],bindings[18],bindings[22],bindings[27],bindings[21],bindings[28],bindings[20],bindings[29],bindings[24],bindings[25]],null);
         watchers[42] = new PropertyWatcher("skill5",{"propertyChange":true},[bindings[52]],null);
         watchers[40] = new PropertyWatcher("skill3",{"propertyChange":true},[bindings[50]],null);
         watchers[45] = new PropertyWatcher("life",{"propertyChange":true},[bindings[55],bindings[74]],null);
         watchers[12] = new PropertyWatcher("isBirth",{"propertyChange":true},[bindings[15],bindings[33],bindings[31],bindings[16]],null);
         watchers[48] = new PropertyWatcher("spellAttack",{"propertyChange":true},[bindings[77],bindings[58]],null);
         watchers[76] = new PropertyWatcher("totalGrowLucky",{"propertyChange":true},[bindings[108]],null);
         watchers[22] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[34],bindings[70]],null);
         watchers[61] = new PropertyWatcher("strength",{"propertyChange":true},[bindings[100],bindings[84]],null);
         watchers[51] = new PropertyWatcher("hit",{"propertyChange":true},[bindings[61],bindings[80]],null);
         watchers[65] = new PropertyWatcher("lucky",{"propertyChange":true},[bindings[108],bindings[88]],null);
         watchers[77] = new PropertyWatcher("maxTotalAbility",{"propertyChange":true},[bindings[122],bindings[111],bindings[109],bindings[114],bindings[112],bindings[110],bindings[113]],null);
         watchers[41] = new PropertyWatcher("skill4",{"propertyChange":true},[bindings[51]],null);
         watchers[50] = new PropertyWatcher("critic",{"propertyChange":true},[bindings[79],bindings[60]],null);
         watchers[54] = new StaticPropertyWatcher("ChooseItem",{"propertyChange":true},[bindings[65]],null);
         watchers[100] = new PropertyWatcher("visitLand3",{"propertyChange":true},[bindings[137]],propertyGetter);
         watchers[18] = new StaticPropertyWatcher("ReBirthTip2",{"propertyChange":true},[bindings[29]],null);
         watchers[3] = new StaticPropertyWatcher("AbilityTrain",{"propertyChange":true},[bindings[4]],null);
         watchers[70] = new PropertyWatcher("growLucky",{"propertyChange":true},[bindings[97],bindings[98]],propertyGetter);
         watchers[84] = new StaticPropertyWatcher("TotalAbility",{"propertyChange":true},[bindings[123]],null);
         watchers[86] = new StaticPropertyWatcher("AdventureNeed",{"propertyChange":true},[bindings[126]],null);
         watchers[4] = new StaticPropertyWatcher("BeastCompose2",{"propertyChange":true},[bindings[6]],null);
         watchers[60] = new StaticPropertyWatcher("Lv",{"propertyChange":true},[bindings[72]],null);
         watchers[67] = new PropertyWatcher("growIntelligence",{"propertyChange":true},[bindings[92],bindings[91]],propertyGetter);
         watchers[78] = new StaticPropertyWatcher("BeastTrainInfo",{"propertyChange":true},[bindings[115]],null);
         watchers[20] = new StaticPropertyWatcher("ReBirth2",{"propertyChange":true},[bindings[30]],null);
         watchers[8] = new StaticPropertyWatcher("Forgive",{"propertyChange":true},[bindings[142],bindings[12]],null);
         watchers[82] = new StaticPropertyWatcher("FeedItem2",{"propertyChange":true},[bindings[120]],null);
         watchers[96] = new StaticPropertyWatcher("AdventureReward",{"propertyChange":true},[bindings[133]],null);
         watchers[85] = new PropertyWatcher("bigLandList",{"propertyChange":true},[bindings[125]],propertyGetter);
         watchers[114] = new StaticPropertyWatcher("perfect2",{"propertyChange":true},[bindings[157]],null);
         watchers[80].updateParent(UILang);
         watchers[95].updateParent(target);
         watchers[58].updateParent(target);
         watchers[115].updateParent(UILang);
         watchers[103].updateParent(target);
         watchers[103].addChild(watchers[107]);
         watchers[103].addChild(watchers[106]);
         watchers[103].addChild(watchers[105]);
         watchers[103].addChild(watchers[104]);
         watchers[97].updateParent(target);
         watchers[99].updateParent(target);
         watchers[16].updateParent(UILang);
         watchers[21].updateParent(UILang);
         watchers[37].updateParent(UILang);
         watchers[43].updateParent(UILang);
         watchers[7].updateParent(UILang);
         watchers[98].updateParent(target);
         watchers[81].updateParent(target);
         watchers[36].updateParent(UILang);
         watchers[0].updateParent(UILang);
         watchers[55].updateParent(DataManager);
         watchers[55].addChild(watchers[56]);
         watchers[56].addChild(watchers[57]);
         watchers[59].updateParent(UILang);
         watchers[101].updateParent(UILang);
         watchers[66].updateParent(target);
         watchers[10].updateParent(UILang);
         watchers[26].updateParent(target);
         watchers[26].addChild(watchers[28]);
         watchers[88].updateParent(UILang);
         watchers[33].updateParent(UILang);
         watchers[116].updateParent(UILang);
         watchers[109].updateParent(target);
         watchers[109].addChild(watchers[113]);
         watchers[109].addChild(watchers[111]);
         watchers[109].addChild(watchers[112]);
         watchers[109].addChild(watchers[110]);
         watchers[92].updateParent(UILang);
         watchers[69].updateParent(target);
         watchers[91].updateParent(target);
         watchers[53].updateParent(target);
         watchers[71].updateParent(UILang);
         watchers[89].updateParent(UILang);
         watchers[102].updateParent(UILang);
         watchers[29].updateParent(target);
         watchers[108].updateParent(UILang);
         watchers[31].updateParent(target);
         watchers[32].parentWatcher = watchers[31];
         watchers[31].addChild(watchers[32]);
         watchers[27].updateParent(UILang);
         watchers[6].updateParent(target);
         watchers[9].updateParent(UILang);
         watchers[68].updateParent(target);
         watchers[93].updateParent(UILang);
         watchers[34].updateParent(target);
         watchers[35].updateParent(target);
         watchers[79].updateParent(target);
         watchers[87].updateParent(target);
         watchers[1].updateParent(target);
         watchers[5].updateParent(UILang);
         watchers[2].updateParent(UILang);
         watchers[30].updateParent(target);
         watchers[11].updateParent(target);
         watchers[11].addChild(watchers[13]);
         watchers[11].addChild(watchers[47]);
         watchers[11].addChild(watchers[39]);
         watchers[11].addChild(watchers[52]);
         watchers[11].addChild(watchers[75]);
         watchers[11].addChild(watchers[49]);
         watchers[11].addChild(watchers[64]);
         watchers[11].addChild(watchers[25]);
         watchers[11].addChild(watchers[38]);
         watchers[11].addChild(watchers[73]);
         watchers[11].addChild(watchers[24]);
         watchers[11].addChild(watchers[14]);
         watchers[11].addChild(watchers[63]);
         watchers[11].addChild(watchers[72]);
         watchers[11].addChild(watchers[74]);
         watchers[11].addChild(watchers[62]);
         watchers[11].addChild(watchers[83]);
         watchers[11].addChild(watchers[46]);
         watchers[11].addChild(watchers[23]);
         watchers[11].addChild(watchers[44]);
         watchers[11].addChild(watchers[15]);
         watchers[11].addChild(watchers[42]);
         watchers[11].addChild(watchers[40]);
         watchers[11].addChild(watchers[45]);
         watchers[11].addChild(watchers[12]);
         watchers[11].addChild(watchers[48]);
         watchers[11].addChild(watchers[76]);
         watchers[11].addChild(watchers[22]);
         watchers[11].addChild(watchers[61]);
         watchers[11].addChild(watchers[51]);
         watchers[11].addChild(watchers[65]);
         watchers[11].addChild(watchers[77]);
         watchers[11].addChild(watchers[41]);
         watchers[11].addChild(watchers[50]);
         watchers[54].updateParent(UILang);
         watchers[100].updateParent(target);
         watchers[18].updateParent(UILang);
         watchers[3].updateParent(UILang);
         watchers[70].updateParent(target);
         watchers[84].updateParent(UILang);
         watchers[86].updateParent(UILang);
         watchers[4].updateParent(UILang);
         watchers[60].updateParent(UILang);
         watchers[67].updateParent(target);
         watchers[78].updateParent(UILang);
         watchers[20].updateParent(UILang);
         watchers[8].updateParent(UILang);
         watchers[82].updateParent(UILang);
         watchers[96].updateParent(UILang);
         watchers[85].updateParent(target);
         watchers[114].updateParent(UILang);
      }
   }
}

