package
{
   import flash.display.Sprite;
   import lang.UILang;
   import manager.DataManager;
   import mx.binding.IWatcherSetupUtil;
   import mx.binding.PropertyWatcher;
   import mx.binding.StaticPropertyWatcher;
   import mx.core.IFlexModuleFactory;
   import ui.item.ItemPanel;
   
   public class _ui_item_ItemPanelWatcherSetupUtil extends Sprite implements IWatcherSetupUtil
   {
      
      public function _ui_item_ItemPanelWatcherSetupUtil()
      {
         super();
      }
      
      public static function init(param1:IFlexModuleFactory) : void
      {
         ItemPanel.watcherSetupUtil = new _ui_item_ItemPanelWatcherSetupUtil();
      }
      
      public function setup(param1:Object, param2:Function, param3:Array, param4:Array) : void
      {
         param4[76] = new StaticPropertyWatcher("Bag",{"propertyChange":true},[param3[80]],null);
         param4[55] = new StaticPropertyWatcher("Bag_B",{"propertyChange":true},[param3[59]],null);
         param4[116] = new StaticPropertyWatcher("Cancel",{"propertyChange":true},[param3[132]],null);
         param4[1] = new PropertyWatcher("hero",{"propertyChange":true},[param3[15],param3[30],param3[43],param3[16],param3[31],param3[123],param3[112],param3[32],param3[34],param3[129],param3[96],param3[117],param3[1],param3[106],param3[29],param3[14],param3[100],param3[47],param3[119],param3[58],param3[18],param3[98],param3[12],param3[27],param3[44],param3[17],param3[2],param3[13],param3[28],param3[38],param3[102],param3[121],param3[57],param3[51],param3[23],param3[104],param3[7],param3[49],param3[54],param3[22],param3[9],param3[53],param3[21],param3[33],param3[6],param3[125],param3[24],param3[42],param3[115],param3[4],param3[19],param3[36],param3[26],param3[55],param3[11],param3[127],param3[108],param3[39],param3[45],param3[20],param3[110],param3[25],param3[10],param3[56],param3[5]],param2);
         param4[4] = new PropertyWatcher("list",{"propertyChange":true},[param3[2]],null);
         param4[5] = new PropertyWatcher("length",{"collectionChange":true},[param3[2]],null);
         param4[7] = new PropertyWatcher("selectHero",{"propertyChange":true},[param3[15],param3[30],param3[43],param3[16],param3[31],param3[123],param3[112],param3[32],param3[34],param3[129],param3[96],param3[117],param3[106],param3[29],param3[14],param3[100],param3[47],param3[119],param3[58],param3[18],param3[98],param3[12],param3[27],param3[44],param3[17],param3[13],param3[28],param3[38],param3[102],param3[121],param3[57],param3[51],param3[23],param3[104],param3[7],param3[49],param3[54],param3[22],param3[9],param3[53],param3[21],param3[33],param3[6],param3[125],param3[24],param3[42],param3[115],param3[4],param3[19],param3[36],param3[26],param3[55],param3[11],param3[127],param3[108],param3[39],param3[45],param3[20],param3[110],param3[25],param3[10],param3[56],param3[5]],null);
         param4[99] = new PropertyWatcher("tiliReduce",{"propertyChange":true},[param3[115]],null);
         param4[8] = new PropertyWatcher("level",{"propertyChange":true},[param3[4]],null);
         param4[47] = new PropertyWatcher("physicalDefence",{"propertyChange":true},[param3[100],param3[49]],null);
         param4[53] = new PropertyWatcher("speed",{"propertyChange":true},[param3[106],param3[57]],null);
         param4[14] = new PropertyWatcher("itemFigure",{"propertyChange":true},[param3[9]],null);
         param4[15] = new PropertyWatcher("armor",{"propertyChange":true},[param3[11],param3[10]],null);
         param4[49] = new PropertyWatcher("spellDefence",{"propertyChange":true},[param3[53],param3[104]],null);
         param4[30] = new PropertyWatcher("horseOverlord",{"propertyChange":true},[param3[32],param3[31]],null);
         param4[31] = new PropertyWatcher("quality",{"propertyChange":true},[param3[32]],null);
         param4[28] = new PropertyWatcher("amuletOverlord",{"propertyChange":true},[param3[30],param3[29]],null);
         param4[29] = new PropertyWatcher("quality",{"propertyChange":true},[param3[30]],null);
         param4[32] = new PropertyWatcher("cloakOverlord",{"propertyChange":true},[param3[34],param3[33]],null);
         param4[33] = new PropertyWatcher("quality",{"propertyChange":true},[param3[34]],null);
         param4[107] = new PropertyWatcher("magicAvoidHurt",{"propertyChange":true},[param3[123]],null);
         param4[37] = new PropertyWatcher("heroQuality",{"propertyChange":true},[param3[38]],null);
         param4[41] = new PropertyWatcher("maxHp",{"propertyChange":true},[param3[42]],null);
         param4[105] = new PropertyWatcher("physicsAvoidHurt",{"propertyChange":true},[param3[121]],null);
         param4[51] = new PropertyWatcher("dodge",{"propertyChange":true},[param3[55],param3[108]],null);
         param4[45] = new PropertyWatcher("physicalAttack",{"propertyChange":true},[param3[47],param3[98]],null);
         param4[24] = new PropertyWatcher("armorOverlord",{"propertyChange":true},[param3[26],param3[25]],null);
         param4[25] = new PropertyWatcher("quality",{"propertyChange":true},[param3[26]],null);
         param4[21] = new PropertyWatcher("overlordPoint",{"propertyChange":true},[param3[22]],null);
         param4[10] = new PropertyWatcher("name",{"propertyChange":true},[param3[6]],null);
         param4[43] = new PropertyWatcher("nextExp",{"propertyChange":true},[param3[45],param3[44]],null);
         param4[109] = new PropertyWatcher("avoidCrit",{"propertyChange":true},[param3[125]],null);
         param4[35] = new PropertyWatcher("jobName",{"propertyChange":true},[param3[36]],null);
         param4[101] = new PropertyWatcher("physicsStrike",{"propertyChange":true},[param3[117]],null);
         param4[54] = new PropertyWatcher("fightingAll",{"propertyChange":true},[param3[58]],null);
         param4[40] = new PropertyWatcher("hp",{"propertyChange":true},[param3[96],param3[43],param3[42]],null);
         param4[17] = new PropertyWatcher("weapon",{"propertyChange":true},[param3[15],param3[14]],null);
         param4[20] = new PropertyWatcher("amulet",{"propertyChange":true},[param3[21],param3[20]],null);
         param4[16] = new PropertyWatcher("misc",{"propertyChange":true},[param3[13],param3[12]],null);
         param4[48] = new PropertyWatcher("spellAttack",{"propertyChange":true},[param3[51],param3[102]],null);
         param4[111] = new PropertyWatcher("block",{"propertyChange":true},[param3[127]],null);
         param4[9] = new PropertyWatcher("nameColor",{"propertyChange":true},[param3[39],param3[7],param3[5]],null);
         param4[18] = new PropertyWatcher("cloak",{"propertyChange":true},[param3[17],param3[16]],null);
         param4[22] = new PropertyWatcher("weaponOverlord",{"propertyChange":true},[param3[23],param3[24]],null);
         param4[23] = new PropertyWatcher("quality",{"propertyChange":true},[param3[24]],null);
         param4[19] = new PropertyWatcher("horse",{"propertyChange":true},[param3[19],param3[18]],null);
         param4[42] = new PropertyWatcher("exp",{"propertyChange":true},[param3[45],param3[44]],null);
         param4[50] = new PropertyWatcher("hit",{"propertyChange":true},[param3[110],param3[54]],null);
         param4[26] = new PropertyWatcher("miscOverlord",{"propertyChange":true},[param3[28],param3[27]],null);
         param4[27] = new PropertyWatcher("quality",{"propertyChange":true},[param3[28]],null);
         param4[103] = new PropertyWatcher("magicStrike",{"propertyChange":true},[param3[119]],null);
         param4[52] = new PropertyWatcher("critic",{"propertyChange":true},[param3[112],param3[56]],null);
         param4[113] = new PropertyWatcher("block2",{"propertyChange":true},[param3[129]],null);
         param4[3] = new PropertyWatcher("page",{"propertyChange":true},[param3[2]],null);
         param4[2] = new PropertyWatcher("showList",{"propertyChange":true},[param3[1]],null);
         param4[39] = new StaticPropertyWatcher("Exp",{"propertyChange":true},[param3[41]],null);
         param4[93] = new StaticPropertyWatcher("Speed",{"propertyChange":true},[param3[105]],null);
         param4[79] = new PropertyWatcher("selectItem",{"propertyChange":true},[param3[85],param3[91]],param2);
         param4[80] = new PropertyWatcher("count",{"propertyChange":true},[param3[85],param3[91]],null);
         param4[78] = new StaticPropertyWatcher("Fragment",{"propertyChange":true},[param3[84]],null);
         param4[84] = new StaticPropertyWatcher("ItemTip",{"propertyChange":true},[param3[89]],null);
         param4[11] = new StaticPropertyWatcher("Instance",null,[param3[8]],null);
         param4[12] = new PropertyWatcher("role",{"propertyChange":true},[param3[8]],null);
         param4[13] = new PropertyWatcher("officialRanklevel",{"propertyChange":true},[param3[8]],null);
         param4[88] = new StaticPropertyWatcher("BasicAbility",{"propertyChange":true},[param3[94]],null);
         param4[38] = new StaticPropertyWatcher("Tili",{"propertyChange":true},[param3[40],param3[95]],null);
         param4[115] = new StaticPropertyWatcher("Sure",{"propertyChange":true},[param3[131]],null);
         param4[44] = new StaticPropertyWatcher("attackTip",{"propertyChange":true},[param3[50],param3[46]],null);
         param4[60] = new StaticPropertyWatcher("Silver",{"propertyChange":true},[param3[64],param3[66]],null);
         param4[87] = new StaticPropertyWatcher("AbilityDes",{"propertyChange":true},[param3[93]],null);
         param4[104] = new StaticPropertyWatcher("PhysicsAvoidHurt",{"propertyChange":true},[param3[120]],null);
         param4[106] = new StaticPropertyWatcher("MagicAvoidHurt",{"propertyChange":true},[param3[122]],null);
         param4[90] = new StaticPropertyWatcher("WuFang",{"propertyChange":true},[param3[99]],null);
         param4[108] = new StaticPropertyWatcher("AvoidCrit3",{"propertyChange":true},[param3[124]],null);
         param4[34] = new StaticPropertyWatcher("Profession",{"propertyChange":true},[param3[35]],null);
         param4[92] = new StaticPropertyWatcher("FaFang",{"propertyChange":true},[param3[103]],null);
         param4[81] = new StaticPropertyWatcher("Use",{"propertyChange":true},[param3[86]],null);
         param4[46] = new StaticPropertyWatcher("defendTip",{"propertyChange":true},[param3[48],param3[52]],null);
         param4[56] = new PropertyWatcher("showData",{"propertyChange":true},[param3[60]],param2);
         param4[82] = new StaticPropertyWatcher("SellSell",{"propertyChange":true},[param3[87]],null);
         param4[57] = new StaticPropertyWatcher("Gold",{"propertyChange":true},[param3[61],param3[63]],null);
         param4[91] = new StaticPropertyWatcher("FaGong",{"propertyChange":true},[param3[101]],null);
         param4[58] = new PropertyWatcher("item",{"propertyChange":true},[param3[64],param3[62],param3[65],param3[70],param3[61],param3[63],param3[78],param3[66]],param2);
         param4[73] = new PropertyWatcher("fragmentAll",{"propertyChange":true},[param3[78]],null);
         param4[74] = new PropertyWatcher("length",{"collectionChange":true},[param3[78]],null);
         param4[61] = new PropertyWatcher("money",{"propertyChange":true},[param3[64],param3[65],param3[66]],null);
         param4[63] = new PropertyWatcher("currentPage",{"propertyChange":true},[param3[70]],null);
         param4[59] = new PropertyWatcher("gold",{"propertyChange":true},[param3[62],param3[61],param3[63]],null);
         param4[71] = new PropertyWatcher("currentFragmentPage",{"propertyChange":true},[param3[78]],null);
         param4[65] = new PropertyWatcher("array",{"propertyChange":true},[param3[70]],null);
         param4[86] = new PropertyWatcher("isDetailOpen",{"propertyChange":true},[param3[92]],param2);
         param4[6] = new StaticPropertyWatcher("SailorMsg_B",{"propertyChange":true},[param3[3]],null);
         param4[114] = new PropertyWatcher("isNameShow",{"propertyChange":true},[param3[130]],param2);
         param4[97] = new StaticPropertyWatcher("ExtraAbility",{"propertyChange":true},[param3[113]],null);
         param4[70] = new PropertyWatcher("inlayMaxPage",{"propertyChange":true},[param3[74]],param2);
         param4[110] = new StaticPropertyWatcher("Block3",{"propertyChange":true},[param3[126]],null);
         param4[0] = new StaticPropertyWatcher("SailorList",{"propertyChange":true},[param3[0]],null);
         param4[89] = new StaticPropertyWatcher("WuGong",{"propertyChange":true},[param3[97]],null);
         param4[77] = new StaticPropertyWatcher("Shell",{"propertyChange":true},[param3[82]],null);
         param4[112] = new StaticPropertyWatcher("Block4",{"propertyChange":true},[param3[128]],null);
         param4[95] = new StaticPropertyWatcher("Hit",{"propertyChange":true},[param3[109]],null);
         param4[36] = new StaticPropertyWatcher("Quality",{"propertyChange":true},[param3[37]],null);
         param4[83] = new StaticPropertyWatcher("Display",{"propertyChange":true},[param3[88]],null);
         param4[69] = new PropertyWatcher("inlayNowPage",{"propertyChange":true},[param3[74]],param2);
         param4[94] = new StaticPropertyWatcher("Dodge",{"propertyChange":true},[param3[107]],null);
         param4[102] = new StaticPropertyWatcher("MagicStrike",{"propertyChange":true},[param3[118]],null);
         param4[85] = new StaticPropertyWatcher("AllUse",{"propertyChange":true},[param3[90]],null);
         param4[98] = new StaticPropertyWatcher("TiliReduce",{"propertyChange":true},[param3[114]],null);
         param4[100] = new StaticPropertyWatcher("PhysicsStrike",{"propertyChange":true},[param3[116]],null);
         param4[96] = new StaticPropertyWatcher("Crit",{"propertyChange":true},[param3[111]],null);
         param4[62] = new PropertyWatcher("bagIndex",{"propertyChange":true},[param3[83],param3[73],param3[68],param3[79],param3[77],param3[75],param3[72],param3[67],param3[81],param3[76],param3[71],param3[69]],param2);
         param4[76].updateParent(UILang);
         param4[55].updateParent(UILang);
         param4[116].updateParent(UILang);
         param4[1].updateParent(param1);
         param4[1].addChild(param4[4]);
         param4[4].addChild(param4[5]);
         param4[1].addChild(param4[7]);
         param4[7].addChild(param4[99]);
         param4[7].addChild(param4[8]);
         param4[7].addChild(param4[47]);
         param4[7].addChild(param4[53]);
         param4[7].addChild(param4[14]);
         param4[7].addChild(param4[15]);
         param4[7].addChild(param4[49]);
         param4[7].addChild(param4[30]);
         param4[30].addChild(param4[31]);
         param4[7].addChild(param4[28]);
         param4[28].addChild(param4[29]);
         param4[7].addChild(param4[32]);
         param4[32].addChild(param4[33]);
         param4[7].addChild(param4[107]);
         param4[7].addChild(param4[37]);
         param4[7].addChild(param4[41]);
         param4[7].addChild(param4[105]);
         param4[7].addChild(param4[51]);
         param4[7].addChild(param4[45]);
         param4[7].addChild(param4[24]);
         param4[24].addChild(param4[25]);
         param4[7].addChild(param4[21]);
         param4[7].addChild(param4[10]);
         param4[7].addChild(param4[43]);
         param4[7].addChild(param4[109]);
         param4[7].addChild(param4[35]);
         param4[7].addChild(param4[101]);
         param4[7].addChild(param4[54]);
         param4[7].addChild(param4[40]);
         param4[7].addChild(param4[17]);
         param4[7].addChild(param4[20]);
         param4[7].addChild(param4[16]);
         param4[7].addChild(param4[48]);
         param4[7].addChild(param4[111]);
         param4[7].addChild(param4[9]);
         param4[7].addChild(param4[18]);
         param4[7].addChild(param4[22]);
         param4[22].addChild(param4[23]);
         param4[7].addChild(param4[19]);
         param4[7].addChild(param4[42]);
         param4[7].addChild(param4[50]);
         param4[7].addChild(param4[26]);
         param4[26].addChild(param4[27]);
         param4[7].addChild(param4[103]);
         param4[7].addChild(param4[52]);
         param4[7].addChild(param4[113]);
         param4[1].addChild(param4[3]);
         param4[1].addChild(param4[2]);
         param4[39].updateParent(UILang);
         param4[93].updateParent(UILang);
         param4[79].updateParent(param1);
         param4[79].addChild(param4[80]);
         param4[78].updateParent(UILang);
         param4[84].updateParent(UILang);
         param4[11].updateParent(DataManager);
         param4[11].addChild(param4[12]);
         param4[12].addChild(param4[13]);
         param4[88].updateParent(UILang);
         param4[38].updateParent(UILang);
         param4[115].updateParent(UILang);
         param4[44].updateParent(UILang);
         param4[60].updateParent(UILang);
         param4[87].updateParent(UILang);
         param4[104].updateParent(UILang);
         param4[106].updateParent(UILang);
         param4[90].updateParent(UILang);
         param4[108].updateParent(UILang);
         param4[34].updateParent(UILang);
         param4[92].updateParent(UILang);
         param4[81].updateParent(UILang);
         param4[46].updateParent(UILang);
         param4[56].updateParent(param1);
         param4[82].updateParent(UILang);
         param4[57].updateParent(UILang);
         param4[91].updateParent(UILang);
         param4[58].updateParent(param1);
         param4[58].addChild(param4[73]);
         param4[73].addChild(param4[74]);
         param4[58].addChild(param4[61]);
         param4[58].addChild(param4[63]);
         param4[58].addChild(param4[59]);
         param4[58].addChild(param4[71]);
         param4[58].addChild(param4[65]);
         param4[86].updateParent(param1);
         param4[6].updateParent(UILang);
         param4[114].updateParent(param1);
         param4[97].updateParent(UILang);
         param4[70].updateParent(param1);
         param4[110].updateParent(UILang);
         param4[0].updateParent(UILang);
         param4[89].updateParent(UILang);
         param4[77].updateParent(UILang);
         param4[112].updateParent(UILang);
         param4[95].updateParent(UILang);
         param4[36].updateParent(UILang);
         param4[83].updateParent(UILang);
         param4[69].updateParent(param1);
         param4[94].updateParent(UILang);
         param4[102].updateParent(UILang);
         param4[85].updateParent(UILang);
         param4[98].updateParent(UILang);
         param4[100].updateParent(UILang);
         param4[96].updateParent(UILang);
         param4[62].updateParent(param1);
      }
   }
}

