package
{
   import constant.Global;
   import flash.display.Sprite;
   import lang.UILang;
   import manager.DataManager;
   import mx.binding.FunctionReturnWatcher;
   import mx.binding.IWatcherSetupUtil;
   import mx.binding.PropertyWatcher;
   import mx.binding.StaticPropertyWatcher;
   import mx.core.IFlexModuleFactory;
   import ui.hero.HeroPanel;
   
   public class _ui_hero_HeroPanelWatcherSetupUtil extends Sprite implements IWatcherSetupUtil
   {
      
      public function _ui_hero_HeroPanelWatcherSetupUtil()
      {
         super();
      }
      
      public static function init(param1:IFlexModuleFactory) : void
      {
         HeroPanel.watcherSetupUtil = new _ui_hero_HeroPanelWatcherSetupUtil();
      }
      
      public function setup(param1:Object, param2:Function, param3:Array, param4:Array) : void
      {
         var target:Object = param1;
         var propertyGetter:Function = param2;
         var bindings:Array = param3;
         var watchers:Array = param4;
         watchers[196] = new PropertyWatcher("trainGold",{"propertyChange":true},[bindings[300]],propertyGetter);
         watchers[194] = new StaticPropertyWatcher("TrainNeed",{"propertyChange":true},[bindings[298]],null);
         watchers[190] = new PropertyWatcher("conIndex",{"propertyChange":true},[bindings[294],bindings[306]],propertyGetter);
         watchers[184] = new StaticPropertyWatcher("TrainP",{"propertyChange":true},[bindings[289]],null);
         watchers[2] = new StaticPropertyWatcher("Skill",{"propertyChange":true},[bindings[2]],null);
         watchers[83] = new StaticPropertyWatcher("AddAtt",{"propertyChange":true},[bindings[161]],null);
         watchers[55] = new StaticPropertyWatcher("AbilityEffect",{"propertyChange":true},[bindings[72]],null);
         watchers[251] = new PropertyWatcher("addLi",{"propertyChange":true},[bindings[354]],propertyGetter);
         watchers[154] = new StaticPropertyWatcher("BoatDress",{"propertyChange":true},[bindings[259]],null);
         watchers[220] = new StaticPropertyWatcher("Perfect",{"propertyChange":true},[bindings[330]],null);
         watchers[4] = new StaticPropertyWatcher("Instance",null,[bindings[322],bindings[232],bindings[15],bindings[326],bindings[19],bindings[9],bindings[319],bindings[285],bindings[6],bindings[320],bindings[230],bindings[12]],null);
         watchers[18] = new PropertyWatcher("hero",{"propertyChange":true},[bindings[326],bindings[19]],null);
         watchers[19] = new PropertyWatcher("list",{"propertyChange":true},[bindings[326],bindings[19]],null);
         watchers[20] = new PropertyWatcher("length",{"collectionChange":true},[bindings[326],bindings[19]],null);
         watchers[5] = new PropertyWatcher("role",{"propertyChange":true},[bindings[322],bindings[232],bindings[15],bindings[326],bindings[19],bindings[9],bindings[319],bindings[285],bindings[6],bindings[320],bindings[230],bindings[12]],null);
         watchers[21] = new PropertyWatcher("heroAmount",{"propertyChange":true},[bindings[326],bindings[19]],null);
         watchers[13] = new PropertyWatcher("officialRanklevel",{"propertyChange":true},[bindings[15]],null);
         watchers[6] = new PropertyWatcher("control",{"propertyChange":true},[bindings[9],bindings[6],bindings[12]],null);
         watchers[7] = new PropertyWatcher("trainBtn",{"propertyChange":true},[bindings[6]],null);
         watchers[9] = new PropertyWatcher("embattleBtn",{"propertyChange":true},[bindings[9]],null);
         watchers[11] = new PropertyWatcher("polishBtn",{"propertyChange":true},[bindings[12]],null);
         watchers[129] = new PropertyWatcher("vip",{"propertyChange":true},[bindings[322],bindings[232],bindings[319],bindings[285],bindings[320],bindings[230]],null);
         watchers[180] = new PropertyWatcher("level",{"propertyChange":true},[bindings[322],bindings[319],bindings[285],bindings[320]],null);
         watchers[130] = new PropertyWatcher("thirdPolish",{"propertyChange":true},[bindings[230]],null);
         watchers[132] = new PropertyWatcher("forthPolish",{"propertyChange":true},[bindings[232]],null);
         watchers[17] = new StaticPropertyWatcher("SailorNum",{"propertyChange":true},[bindings[326],bindings[19]],null);
         watchers[212] = new StaticPropertyWatcher("Gold100GetExp4",{"propertyChange":true},[bindings[316]],null);
         watchers[258] = new PropertyWatcher("ti",{"propertyChange":true},[bindings[363]],propertyGetter);
         watchers[164] = new StaticPropertyWatcher("PhDef",{"propertyChange":true},[bindings[270]],null);
         watchers[276] = new StaticPropertyWatcher("MagicAvoidHurt",{"propertyChange":true},[bindings[388]],null);
         watchers[275] = new StaticPropertyWatcher("PhysicsAvoidHurt",{"propertyChange":true},[bindings[386]],null);
         watchers[256] = new PropertyWatcher("addZhi",{"propertyChange":true},[bindings[360]],propertyGetter);
         watchers[156] = new StaticPropertyWatcher("BoatUpGrate",{"propertyChange":true},[bindings[261]],null);
         watchers[261] = new PropertyWatcher("addTi",{"propertyChange":true},[bindings[366]],propertyGetter);
         watchers[277] = new StaticPropertyWatcher("AvoidCrit3",{"propertyChange":true},[bindings[390]],null);
         watchers[114] = new StaticPropertyWatcher("NewAttri",{"propertyChange":true},[bindings[198]],null);
         watchers[77] = new StaticPropertyWatcher("WarValue",{"propertyChange":true},[bindings[125]],null);
         watchers[146] = new StaticPropertyWatcher("ShipTips2",{"propertyChange":true},[bindings[250]],null);
         watchers[159] = new StaticPropertyWatcher("FiAttri",{"propertyChange":true},[bindings[265]],null);
         watchers[170] = new StaticPropertyWatcher("Life",{"propertyChange":true},[bindings[276]],null);
         watchers[195] = new PropertyWatcher("trainSilver",{"propertyChange":true},[bindings[299]],propertyGetter);
         watchers[250] = new PropertyWatcher("addLiStr",{"propertyChange":true},[bindings[354]],propertyGetter);
         watchers[100] = new StaticPropertyWatcher("AttriFoster_B",{"propertyChange":true},[bindings[180]],null);
         watchers[206] = new PropertyWatcher("getExp",{"propertyChange":true},[bindings[311]],propertyGetter);
         watchers[191] = new StaticPropertyWatcher("TrainTime2",{"propertyChange":true},[bindings[295]],null);
         watchers[177] = new StaticPropertyWatcher("TrainCostTip1",{"propertyChange":true},[bindings[282]],null);
         watchers[155] = new StaticPropertyWatcher("BoatDressTip",{"propertyChange":true},[bindings[260]],null);
         watchers[223] = new StaticPropertyWatcher("PassInSailor",{"propertyChange":true},[bindings[333]],null);
         watchers[178] = new StaticPropertyWatcher("TrainCostTip2",{"propertyChange":true},[bindings[283]],null);
         watchers[179] = new StaticPropertyWatcher("TrainCostTip3",{"propertyChange":true},[bindings[284]],null);
         watchers[270] = new StaticPropertyWatcher("ExtraAbility",{"propertyChange":true},[bindings[379]],null);
         watchers[199] = new StaticPropertyWatcher("StartTrain",{"propertyChange":true},[bindings[303]],null);
         watchers[133] = new StaticPropertyWatcher("WashAttri",{"propertyChange":true},[bindings[233]],null);
         watchers[141] = new StaticPropertyWatcher("SailorOnField_B",{"propertyChange":true},[bindings[245]],null);
         watchers[259] = new PropertyWatcher("tiColor",{"propertyChange":true},[bindings[364]],propertyGetter);
         watchers[278] = new StaticPropertyWatcher("Block3",{"propertyChange":true},[bindings[392]],null);
         watchers[260] = new PropertyWatcher("addTiStr",{"propertyChange":true},[bindings[366]],propertyGetter);
         watchers[263] = new PropertyWatcher("min",{"propertyChange":true},[bindings[369]],propertyGetter);
         watchers[279] = new StaticPropertyWatcher("Block4",{"propertyChange":true},[bindings[394]],null);
         watchers[186] = new PropertyWatcher("trainPosition",{"propertyChange":true},[bindings[289]],propertyGetter);
         watchers[198] = new PropertyWatcher("willGetExp",{"propertyChange":true},[bindings[302]],propertyGetter);
         watchers[252] = new PropertyWatcher("addLiColor",{"propertyChange":true},[bindings[355]],propertyGetter);
         watchers[30] = new StaticPropertyWatcher("Display",{"propertyChange":true},[bindings[83],bindings[28],bindings[121],bindings[48]],null);
         watchers[1] = new PropertyWatcher("currentIndex",{"propertyChange":true},[bindings[239],bindings[287],bindings[8],bindings[11],bindings[16],bindings[263],bindings[3],bindings[323],bindings[22],bindings[375],bindings[244],bindings[77],bindings[96],bindings[292],bindings[1],bindings[376],bindings[179],bindings[78],bindings[14],bindings[42],bindings[5],bindings[115]],propertyGetter);
         watchers[185] = new PropertyWatcher("usePosition",{"propertyChange":true},[bindings[289]],propertyGetter);
         watchers[152] = new StaticPropertyWatcher("shipNameArr",{"propertyChange":true},[bindings[258]],null);
         watchers[153] = new FunctionReturnWatcher("getItemAt",target,function():Array
         {
            return [target.hero.currentShape - 1];
         },{"collectionChange":true},[bindings[258]],null);
         watchers[200] = new StaticPropertyWatcher("TrainLvTip",{"propertyChange":true},[bindings[305]],null);
         watchers[264] = new PropertyWatcher("minColor",{"propertyChange":true},[bindings[370]],propertyGetter);
         watchers[32] = new StaticPropertyWatcher("Job",{"propertyChange":true},[bindings[30],bindings[85],bindings[50],bindings[123],bindings[86]],null);
         watchers[274] = new StaticPropertyWatcher("MagicStrike",{"propertyChange":true},[bindings[384]],null);
         watchers[145] = new StaticPropertyWatcher("ShipTips1",{"propertyChange":true},[bindings[248]],null);
         watchers[137] = new StaticPropertyWatcher("LeftPoint",{"propertyChange":true},[bindings[241]],null);
         watchers[219] = new PropertyWatcher("coverPassOn",{"propertyChange":true},[bindings[368],bindings[338],bindings[359],bindings[374],bindings[342],bindings[362],bindings[371],bindings[328],bindings[339],bindings[356],bindings[329],bindings[353],bindings[340],bindings[365]],propertyGetter);
         watchers[232] = new PropertyWatcher("level",{"propertyChange":true},[bindings[340]],null);
         watchers[229] = new PropertyWatcher("name",{"propertyChange":true},[bindings[338]],null);
         watchers[230] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[339]],null);
         watchers[239] = new PropertyWatcher("jobName",{"propertyChange":true},[bindings[342]],null);
         watchers[59] = new PropertyWatcher("_selectHero",{"propertyChange":true},[bindings[107],bindings[168],bindings[151],bindings[158],bindings[104],bindings[99],bindings[150],bindings[112],bindings[113],bindings[159],bindings[144],bindings[176],bindings[149],bindings[105],bindings[147],bindings[106],bindings[152],bindings[157],bindings[308],bindings[170],bindings[309],bindings[111],bindings[100],bindings[178],bindings[146],bindings[114],bindings[154],bindings[145],bindings[155],bindings[108],bindings[103],bindings[172],bindings[166],bindings[148],bindings[109],bindings[156],bindings[102],bindings[164],bindings[110],bindings[174],bindings[153],bindings[101]],propertyGetter);
         watchers[202] = new PropertyWatcher("trainTime",{"propertyChange":true},[bindings[308]],null);
         watchers[60] = new PropertyWatcher("hero",{"propertyChange":true},[bindings[107],bindings[168],bindings[151],bindings[158],bindings[104],bindings[99],bindings[150],bindings[112],bindings[113],bindings[159],bindings[144],bindings[176],bindings[149],bindings[105],bindings[147],bindings[106],bindings[152],bindings[157],bindings[170],bindings[111],bindings[100],bindings[178],bindings[146],bindings[114],bindings[154],bindings[145],bindings[155],bindings[108],bindings[103],bindings[172],bindings[166],bindings[148],bindings[109],bindings[156],bindings[102],bindings[164],bindings[110],bindings[174],bindings[153],bindings[101]],null);
         watchers[74] = new PropertyWatcher("criticQuality",{"propertyChange":true},[bindings[112],bindings[157]],null);
         watchers[63] = new PropertyWatcher("physicalDefence",{"propertyChange":true},[bindings[146],bindings[101]],null);
         watchers[70] = new PropertyWatcher("hitQuality",{"propertyChange":true},[bindings[108],bindings[153]],null);
         watchers[75] = new PropertyWatcher("speed",{"propertyChange":true},[bindings[158],bindings[113]],null);
         watchers[76] = new PropertyWatcher("speedQuality",{"propertyChange":true},[bindings[114],bindings[159]],null);
         watchers[72] = new PropertyWatcher("dodgeQuality",{"propertyChange":true},[bindings[110],bindings[155]],null);
         watchers[67] = new PropertyWatcher("spellDefence",{"propertyChange":true},[bindings[105],bindings[150]],null);
         watchers[99] = new PropertyWatcher("block2Quality",{"propertyChange":true},[bindings[178]],null);
         watchers[97] = new PropertyWatcher("blockQuality",{"propertyChange":true},[bindings[176]],null);
         watchers[65] = new PropertyWatcher("spellAttack",{"propertyChange":true},[bindings[148],bindings[103]],null);
         watchers[66] = new PropertyWatcher("spellAttackQuality",{"propertyChange":true},[bindings[149],bindings[104]],null);
         watchers[62] = new PropertyWatcher("physicalAttackQuality",{"propertyChange":true},[bindings[100],bindings[145]],null);
         watchers[68] = new PropertyWatcher("spellDefenceQuality",{"propertyChange":true},[bindings[151],bindings[106]],null);
         watchers[93] = new PropertyWatcher("magicAvoidHurtQuality",{"propertyChange":true},[bindings[172]],null);
         watchers[87] = new PropertyWatcher("physicsStrikeQuality",{"propertyChange":true},[bindings[166]],null);
         watchers[69] = new PropertyWatcher("hit",{"propertyChange":true},[bindings[107],bindings[152]],null);
         watchers[89] = new PropertyWatcher("magicStrikeQuality",{"propertyChange":true},[bindings[168]],null);
         watchers[71] = new PropertyWatcher("dodge",{"propertyChange":true},[bindings[109],bindings[154]],null);
         watchers[61] = new PropertyWatcher("physicalAttack",{"propertyChange":true},[bindings[99],bindings[144]],null);
         watchers[95] = new PropertyWatcher("avoidCritQuality",{"propertyChange":true},[bindings[174]],null);
         watchers[85] = new PropertyWatcher("angerQuality",{"propertyChange":true},[bindings[164]],null);
         watchers[64] = new PropertyWatcher("physicalDefenceQuality",{"propertyChange":true},[bindings[102],bindings[147]],null);
         watchers[73] = new PropertyWatcher("critic",{"propertyChange":true},[bindings[111],bindings[156]],null);
         watchers[91] = new PropertyWatcher("physicsAvoidHurtQuality",{"propertyChange":true},[bindings[170]],null);
         watchers[203] = new PropertyWatcher("clock",{"propertyChange":true},[bindings[309]],null);
         watchers[204] = new PropertyWatcher("time",{"propertyChange":true},[bindings[309]],null);
         watchers[26] = new StaticPropertyWatcher("Lv",{"propertyChange":true},[bindings[79],bindings[117],bindings[24],bindings[44]],null);
         watchers[271] = new StaticPropertyWatcher("TiliReduce",{"propertyChange":true},[bindings[380]],null);
         watchers[12] = new StaticPropertyWatcher("PassOn",{"propertyChange":true},[bindings[13]],null);
         watchers[224] = new StaticPropertyWatcher("PassOnSailor",{"propertyChange":true},[bindings[334]],null);
         watchers[273] = new StaticPropertyWatcher("PhysicsStrike",{"propertyChange":true},[bindings[382]],null);
         watchers[205] = new StaticPropertyWatcher("QuickTrain_B",{"propertyChange":true},[bindings[310]],null);
         watchers[81] = new StaticPropertyWatcher("SailorAttri_E",{"propertyChange":true},[bindings[141]],null);
         watchers[193] = new StaticPropertyWatcher("TrainRate",{"propertyChange":true},[bindings[297]],null);
         watchers[58] = new StaticPropertyWatcher("AbilityNum",{"propertyChange":true},[bindings[143],bindings[162],bindings[98]],null);
         watchers[0] = new StaticPropertyWatcher("MarinerInfo",{"propertyChange":true},[bindings[0]],null);
         watchers[22] = new StaticPropertyWatcher("Fire",{"propertyChange":true},[bindings[20]],null);
         watchers[162] = new StaticPropertyWatcher("MagAtt",{"propertyChange":true},[bindings[268]],null);
         watchers[57] = new StaticPropertyWatcher("BasicAttri",{"propertyChange":true},[bindings[97],bindings[142]],null);
         watchers[43] = new PropertyWatcher("needAbilityChange",{"propertyChange":true},[bindings[41]],propertyGetter);
         watchers[15] = new PropertyWatcher("hero",{"propertyChange":true},[bindings[62],bindings[30],bindings[190],bindings[246],bindings[214],bindings[171],bindings[95],bindings[123],bindings[223],bindings[213],bindings[86],bindings[286],bindings[59],bindings[118],bindings[32],bindings[225],bindings[169],bindings[224],bindings[85],bindings[117],bindings[201],bindings[396],bindings[61],bindings[189],bindings[257],bindings[234],bindings[68],bindings[82],bindings[58],bindings[119],bindings[258],bindings[203],bindings[63],bindings[194],bindings[226],bindings[140],bindings[81],bindings[27],bindings[191],bindings[279],bindings[64],bindings[212],bindings[38],bindings[57],bindings[247],bindings[120],bindings[163],bindings[200],bindings[94],bindings[199],bindings[193],bindings[53],bindings[65],bindings[33],bindings[381],bindings[280],bindings[206],bindings[93],bindings[24],bindings[88],bindings[242],bindings[195],bindings[36],bindings[383],bindings[26],bindings[67],bindings[127],bindings[167],bindings[236]
         ,bindings[281],bindings[204],bindings[45],bindings[197],bindings[74],bindings[238],bindings[46],bindings[25],bindings[56],bindings[202],bindings[79],bindings[207],bindings[304],bindings[241],bindings[80],bindings[251],bindings[271],bindings[187],bindings[208],bindings[73],bindings[41],bindings[70],bindings[385],bindings[47],bindings[131],bindings[210],bindings[273],bindings[75],bindings[186],bindings[231],bindings[175],bindings[18],bindings[209],bindings[387],bindings[66],bindings[44],bindings[205],bindings[229],bindings[165],bindings[228],bindings[37],bindings[185],bindings[269],bindings[249],bindings[227],bindings[222],bindings[215],bindings[277],bindings[177],bindings[182],bindings[391],bindings[134],bindings[393],bindings[275],bindings[21],bindings[137],bindings[221],bindings[253],bindings[216],bindings[211],bindings[52],bindings[395],bindings[183],bindings[139],bindings[218],bindings[50],bindings[267],bindings[219],bindings[39],bindings[173],bindings[256],bindings[92],bindings[220]
         ,bindings[89],bindings[133],bindings[325],bindings[389],bindings[217],bindings[138]],propertyGetter);
         watchers[281] = new PropertyWatcher("list",{"propertyChange":true},[bindings[396]],null);
         watchers[282] = new PropertyWatcher("length",{"collectionChange":true},[bindings[396]],null);
         watchers[23] = new PropertyWatcher("selectHero",{"propertyChange":true},[bindings[62],bindings[30],bindings[190],bindings[214],bindings[171],bindings[95],bindings[123],bindings[223],bindings[213],bindings[86],bindings[59],bindings[118],bindings[32],bindings[225],bindings[169],bindings[224],bindings[117],bindings[85],bindings[201],bindings[61],bindings[189],bindings[234],bindings[68],bindings[82],bindings[58],bindings[119],bindings[203],bindings[63],bindings[194],bindings[226],bindings[140],bindings[81],bindings[27],bindings[191],bindings[64],bindings[212],bindings[38],bindings[57],bindings[120],bindings[163],bindings[200],bindings[94],bindings[199],bindings[193],bindings[53],bindings[65],bindings[33],bindings[381],bindings[206],bindings[93],bindings[24],bindings[88],bindings[242],bindings[195],bindings[36],bindings[383],bindings[26],bindings[67],bindings[127],bindings[167],bindings[236],bindings[204],bindings[45],bindings[197],bindings[74],bindings[238],bindings[46],bindings[25],bindings[56]
         ,bindings[202],bindings[79],bindings[207],bindings[304],bindings[241],bindings[80],bindings[187],bindings[208],bindings[73],bindings[41],bindings[70],bindings[385],bindings[47],bindings[131],bindings[210],bindings[75],bindings[186],bindings[231],bindings[175],bindings[209],bindings[387],bindings[66],bindings[44],bindings[205],bindings[229],bindings[165],bindings[228],bindings[37],bindings[185],bindings[227],bindings[222],bindings[215],bindings[177],bindings[182],bindings[391],bindings[134],bindings[393],bindings[21],bindings[137],bindings[221],bindings[216],bindings[211],bindings[52],bindings[395],bindings[183],bindings[139],bindings[218],bindings[50],bindings[219],bindings[39],bindings[173],bindings[92],bindings[220],bindings[89],bindings[133],bindings[389],bindings[217],bindings[138]],null);
         watchers[272] = new PropertyWatcher("tiliReduce",{"propertyChange":true},[bindings[381]],null);
         watchers[127] = new PropertyWatcher("secondCost",{"propertyChange":true},[bindings[228]],null);
         watchers[27] = new PropertyWatcher("level",{"propertyChange":true},[bindings[79],bindings[117],bindings[24],bindings[44]],null);
         watchers[138] = new PropertyWatcher("skillPoint",{"propertyChange":true},[bindings[241]],null);
         watchers[109] = new PropertyWatcher("totalGrowStamina",{"propertyChange":true},[bindings[193],bindings[191]],null);
         watchers[106] = new PropertyWatcher("totalGrowIntelligence",{"propertyChange":true},[bindings[189],bindings[187]],null);
         watchers[120] = new PropertyWatcher("addStamina",{"propertyChange":true},[bindings[215],bindings[213],bindings[219],bindings[217]],null);
         watchers[118] = new PropertyWatcher("addIntelligence",{"propertyChange":true},[bindings[210],bindings[212],bindings[206],bindings[208]],null);
         watchers[92] = new PropertyWatcher("magicAvoidHurt",{"propertyChange":true},[bindings[171],bindings[389]],null);
         watchers[103] = new PropertyWatcher("totalGrowStrength",{"propertyChange":true},[bindings[183],bindings[185]],null);
         watchers[112] = new PropertyWatcher("totalGrowAgility",{"propertyChange":true},[bindings[195],bindings[197]],null);
         watchers[35] = new PropertyWatcher("heroQuality",{"propertyChange":true},[bindings[32],bindings[133],bindings[52],bindings[88]],null);
         watchers[39] = new PropertyWatcher("maxHp",{"propertyChange":true},[bindings[36],bindings[92],bindings[137],bindings[56]],null);
         watchers[90] = new PropertyWatcher("physicsAvoidHurt",{"propertyChange":true},[bindings[169],bindings[387]],null);
         watchers[111] = new PropertyWatcher("growAgility",{"propertyChange":true},[bindings[222],bindings[195],bindings[224],bindings[197],bindings[194],bindings[226]],null);
         watchers[29] = new PropertyWatcher("name",{"propertyChange":true},[bindings[119],bindings[26],bindings[46],bindings[81]],null);
         watchers[80] = new PropertyWatcher("overlordPoint",{"propertyChange":true},[bindings[131]],null);
         watchers[122] = new PropertyWatcher("addAgility",{"propertyChange":true},[bindings[222],bindings[224],bindings[220],bindings[226]],null);
         watchers[41] = new PropertyWatcher("nextExp",{"propertyChange":true},[bindings[94],bindings[58],bindings[139],bindings[38],bindings[95],bindings[140],bindings[39],bindings[59]],null);
         watchers[33] = new PropertyWatcher("jobName",{"propertyChange":true},[bindings[30],bindings[85],bindings[50],bindings[123],bindings[86]],null);
         watchers[94] = new PropertyWatcher("avoidCrit",{"propertyChange":true},[bindings[173],bindings[391]],null);
         watchers[24] = new PropertyWatcher("isRole",{"propertyChange":true},[bindings[304],bindings[21]],null);
         watchers[102] = new PropertyWatcher("growStrength",{"propertyChange":true},[bindings[205],bindings[183],bindings[203],bindings[201],bindings[182],bindings[185]],null);
         watchers[116] = new PropertyWatcher("hasNew",{"propertyChange":true},[bindings[200],bindings[207],bindings[214],bindings[218],bindings[209],bindings[223],bindings[236],bindings[204],bindings[225],bindings[221],bindings[238],bindings[211],bindings[216],bindings[202],bindings[234]],null);
         watchers[78] = new PropertyWatcher("fightingAll",{"propertyChange":true},[bindings[127]],null);
         watchers[86] = new PropertyWatcher("physicsStrike",{"propertyChange":true},[bindings[383],bindings[165]],null);
         watchers[38] = new PropertyWatcher("hp",{"propertyChange":true},[bindings[36],bindings[92],bindings[137],bindings[93],bindings[57],bindings[37],bindings[56],bindings[138]],null);
         watchers[139] = new PropertyWatcher("skills",{"propertyChange":true},[bindings[242]],null);
         watchers[84] = new PropertyWatcher("anger",{"propertyChange":true},[bindings[163]],null);
         watchers[28] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[45],bindings[134],bindings[47],bindings[82],bindings[53],bindings[33],bindings[89],bindings[80],bindings[25],bindings[120],bindings[118],bindings[27]],null);
         watchers[96] = new PropertyWatcher("block",{"propertyChange":true},[bindings[393],bindings[175]],null);
         watchers[46] = new PropertyWatcher("demon",{"propertyChange":true},[bindings[64],bindings[73],bindings[68],bindings[62],bindings[75],bindings[70],bindings[74],bindings[67],bindings[61],bindings[63],bindings[66]],null);
         watchers[47] = new PropertyWatcher("skill",{"propertyChange":true},[bindings[73],bindings[62],bindings[70],bindings[67],bindings[61],bindings[66]],null);
         watchers[56] = new PropertyWatcher("desc2",{"propertyChange":true},[bindings[73]],null);
         watchers[51] = new PropertyWatcher("url",{"propertyChange":true},[bindings[67]],null);
         watchers[53] = new PropertyWatcher("desc3",{"propertyChange":true},[bindings[70]],null);
         watchers[48] = new PropertyWatcher("name",{"propertyChange":true},[bindings[62],bindings[61]],null);
         watchers[50] = new PropertyWatcher("activation",{"propertyChange":true},[bindings[64],bindings[68],bindings[75],bindings[74],bindings[63]],null);
         watchers[40] = new PropertyWatcher("exp",{"propertyChange":true},[bindings[94],bindings[58],bindings[139],bindings[38],bindings[95],bindings[140],bindings[39],bindings[59]],null);
         watchers[131] = new PropertyWatcher("fourthCost",{"propertyChange":true},[bindings[231]],null);
         watchers[115] = new PropertyWatcher("addStrength",{"propertyChange":true},[bindings[205],bindings[203],bindings[201],bindings[199]],null);
         watchers[105] = new PropertyWatcher("growIntelligence",{"propertyChange":true},[bindings[210],bindings[212],bindings[186],bindings[189],bindings[208],bindings[187]],null);
         watchers[128] = new PropertyWatcher("thirdCost",{"propertyChange":true},[bindings[229]],null);
         watchers[125] = new PropertyWatcher("firstCost",{"propertyChange":true},[bindings[227]],null);
         watchers[88] = new PropertyWatcher("magicStrike",{"propertyChange":true},[bindings[167],bindings[385]],null);
         watchers[98] = new PropertyWatcher("block2",{"propertyChange":true},[bindings[395],bindings[177]],null);
         watchers[108] = new PropertyWatcher("growStamina",{"propertyChange":true},[bindings[215],bindings[193],bindings[190],bindings[219],bindings[217],bindings[191]],null);
         watchers[45] = new PropertyWatcher("quality",null,[bindings[62],bindings[65],bindings[74],bindings[61]],null);
         watchers[280] = new PropertyWatcher("page",{"propertyChange":true},[bindings[396]],null);
         watchers[142] = new PropertyWatcher("currentEmbattle",{"propertyChange":true},[bindings[277],bindings[273],bindings[246],bindings[267],bindings[251],bindings[271],bindings[281],bindings[279],bindings[275],bindings[280],bindings[253],bindings[257],bindings[247],bindings[269],bindings[249]],null);
         watchers[144] = new PropertyWatcher("level",{"propertyChange":true},[bindings[253],bindings[251],bindings[247],bindings[249]],null);
         watchers[165] = new PropertyWatcher("physicalDefence",{"propertyChange":true},[bindings[271]],null);
         watchers[169] = new PropertyWatcher("speed",{"propertyChange":true},[bindings[275]],null);
         watchers[151] = new PropertyWatcher("fightingAll",{"propertyChange":true},[bindings[257]],null);
         watchers[167] = new PropertyWatcher("spellDefence",{"propertyChange":true},[bindings[273]],null);
         watchers[143] = new PropertyWatcher("heros",{"propertyChange":true},[bindings[246]],null);
         watchers[163] = new PropertyWatcher("spellAttack",{"propertyChange":true},[bindings[269]],null);
         watchers[176] = new PropertyWatcher("maxExp",{"propertyChange":true},[bindings[280],bindings[281]],null);
         watchers[174] = new PropertyWatcher("addCristResit",{"propertyChange":true},[bindings[279]],null);
         watchers[175] = new PropertyWatcher("nowExp",{"propertyChange":true},[bindings[280],bindings[281]],null);
         watchers[172] = new PropertyWatcher("addHealth",{"propertyChange":true},[bindings[277]],null);
         watchers[171] = new PropertyWatcher("healthPoint",{"propertyChange":true},[bindings[277]],null);
         watchers[161] = new PropertyWatcher("physicalAttack",{"propertyChange":true},[bindings[267]],null);
         watchers[183] = new PropertyWatcher("formationCard",{"propertyChange":true},[bindings[286]],null);
         watchers[150] = new PropertyWatcher("currentShape",{"propertyChange":true},[bindings[256],bindings[258]],null);
         watchers[16] = new PropertyWatcher("showList",{"propertyChange":true},[bindings[18],bindings[325]],null);
         watchers[113] = new StaticPropertyWatcher("AddATT6",{"propertyChange":true},[bindings[196]],null);
         watchers[267] = new PropertyWatcher("addMinColor",{"propertyChange":true},[bindings[373]],propertyGetter);
         watchers[37] = new StaticPropertyWatcher("Exp",{"propertyChange":true},[bindings[136],bindings[55],bindings[35],bindings[91]],null);
         watchers[168] = new StaticPropertyWatcher("Speed",{"propertyChange":true},[bindings[274]],null);
         watchers[197] = new StaticPropertyWatcher("GainExp",{"propertyChange":true},[bindings[311],bindings[301]],null);
         watchers[147] = new StaticPropertyWatcher("ShipTips3",{"propertyChange":true},[bindings[252]],null);
         watchers[266] = new PropertyWatcher("addMin",{"propertyChange":true},[bindings[372]],propertyGetter);
         watchers[31] = new StaticPropertyWatcher("SailorMsgOpen",{"propertyChange":true},[bindings[122],bindings[84],bindings[29],bindings[49]],null);
         watchers[36] = new StaticPropertyWatcher("Tili",{"propertyChange":true},[bindings[90],bindings[34],bindings[135],bindings[54]],null);
         watchers[44] = new StaticPropertyWatcher("Special",{"propertyChange":true},[bindings[60]],null);
         watchers[187] = new StaticPropertyWatcher("AddTrainP",{"propertyChange":true},[bindings[290]],null);
         watchers[157] = new StaticPropertyWatcher("BoatDressTip2",{"propertyChange":true},[bindings[262]],null);
         watchers[222] = new StaticPropertyWatcher("PassOnExplain1",{"propertyChange":true},[bindings[332]],null);
         watchers[269] = new StaticPropertyWatcher("AbilityDes",{"propertyChange":true},[bindings[378]],null);
         watchers[208] = new PropertyWatcher("token",{"propertyChange":true},[bindings[312]],propertyGetter);
         watchers[188] = new PropertyWatcher("heros",{"propertyChange":true},[bindings[291]],propertyGetter);
         watchers[236] = new FunctionReturnWatcher("floor",target,function():Array
         {
            return [target.passOn.level * 0.7];
         },null,[bindings[340]],null);
         watchers[140] = new StaticPropertyWatcher("SkillPreview",{"propertyChange":true},[bindings[243]],null);
         watchers[124] = new StaticPropertyWatcher("SeriousFame",{"propertyChange":true},[bindings[227]],null);
         watchers[10] = new StaticPropertyWatcher("Foster",{"propertyChange":true},[bindings[10]],null);
         watchers[253] = new PropertyWatcher("zhi",{"propertyChange":true},[bindings[357]],propertyGetter);
         watchers[257] = new PropertyWatcher("addZhiColor",{"propertyChange":true},[bindings[361]],propertyGetter);
         watchers[149] = new StaticPropertyWatcher("BoatDress_B",{"propertyChange":true},[bindings[255]],null);
         watchers[201] = new StaticPropertyWatcher("TrainTime",{"propertyChange":true},[bindings[307]],null);
         watchers[231] = new PropertyWatcher("perfect",{"propertyChange":true},[bindings[371],bindings[356],bindings[368],bindings[359],bindings[353],bindings[374],bindings[362],bindings[340],bindings[365]],propertyGetter);
         watchers[213] = new StaticPropertyWatcher("TrainToCool",{"propertyChange":true},[bindings[317]],null);
         watchers[189] = new StaticPropertyWatcher("SailorTrain_B",{"propertyChange":true},[bindings[293]],null);
         watchers[216] = new StaticPropertyWatcher("Gold100GetExp",{"propertyChange":true},[bindings[319]],null);
         watchers[135] = new StaticPropertyWatcher("Replace",{"propertyChange":true},[bindings[237]],null);
         watchers[221] = new StaticPropertyWatcher("PayLevelPassOn",{"propertyChange":true},[bindings[331]],null);
         watchers[54] = new StaticPropertyWatcher("SpecialSkillPlace",{"propertyChange":true},[bindings[71]],null);
         watchers[126] = new StaticPropertyWatcher("Gold",{"propertyChange":true},[bindings[229],bindings[231],bindings[228]],null);
         watchers[148] = new StaticPropertyWatcher("ShipTips4",{"propertyChange":true},[bindings[254]],null);
         watchers[209] = new StaticPropertyWatcher("QuickTrain",{"propertyChange":true},[bindings[313]],null);
         watchers[158] = new StaticPropertyWatcher("BoatUpg_B",{"propertyChange":true},[bindings[264]],null);
         watchers[268] = new PropertyWatcher("isDetailOpen",{"propertyChange":true},[bindings[377]],propertyGetter);
         watchers[52] = new StaticPropertyWatcher("AbilityDescribe",{"propertyChange":true},[bindings[69]],null);
         watchers[25] = new StaticPropertyWatcher("SailorMsg_B",{"propertyChange":true},[bindings[23],bindings[43],bindings[116]],null);
         watchers[101] = new StaticPropertyWatcher("OldAttri",{"propertyChange":true},[bindings[181]],null);
         watchers[160] = new StaticPropertyWatcher("PhAtt",{"propertyChange":true},[bindings[266]],null);
         watchers[192] = new StaticPropertyWatcher("TrainTime3",{"propertyChange":true},[bindings[296]],null);
         watchers[82] = new StaticPropertyWatcher("SailorAttri_F",{"propertyChange":true},[bindings[160]],null);
         watchers[218] = new PropertyWatcher("passOn",{"propertyChange":true},[bindings[337],bindings[341],bindings[346],bindings[336],bindings[327],bindings[345],bindings[350],bindings[335],bindings[343],bindings[329],bindings[349],bindings[348],bindings[344],bindings[340],bindings[347]],propertyGetter);
         watchers[240] = new PropertyWatcher("growStrength",{"propertyChange":true},[bindings[343],bindings[344]],null);
         watchers[227] = new PropertyWatcher("level",{"propertyChange":true},[bindings[337],bindings[340]],null);
         watchers[245] = new PropertyWatcher("totalGrowStamina",{"propertyChange":true},[bindings[348]],null);
         watchers[241] = new PropertyWatcher("totalGrowStrength",{"propertyChange":true},[bindings[344]],null);
         watchers[247] = new PropertyWatcher("totalGrowAgility",{"propertyChange":true},[bindings[350]],null);
         watchers[242] = new PropertyWatcher("growIntelligence",{"propertyChange":true},[bindings[346],bindings[345]],null);
         watchers[246] = new PropertyWatcher("growAgility",{"propertyChange":true},[bindings[349],bindings[350]],null);
         watchers[225] = new PropertyWatcher("name",{"propertyChange":true},[bindings[335]],null);
         watchers[226] = new PropertyWatcher("nameColor",{"propertyChange":true},[bindings[336]],null);
         watchers[244] = new PropertyWatcher("growStamina",{"propertyChange":true},[bindings[348],bindings[347]],null);
         watchers[243] = new PropertyWatcher("totalGrowIntelligence",{"propertyChange":true},[bindings[346]],null);
         watchers[238] = new PropertyWatcher("jobName",{"propertyChange":true},[bindings[341]],null);
         watchers[14] = new StaticPropertyWatcher("SailorList",{"propertyChange":true},[bindings[17],bindings[324],bindings[288]],null);
         watchers[254] = new PropertyWatcher("zhiColor",{"propertyChange":true},[bindings[358]],propertyGetter);
         watchers[110] = new StaticPropertyWatcher("AddATT7",{"propertyChange":true},[bindings[192]],null);
         watchers[107] = new StaticPropertyWatcher("AddATT8",{"propertyChange":true},[bindings[188]],null);
         watchers[3] = new StaticPropertyWatcher("Train",{"propertyChange":true},[bindings[4]],null);
         watchers[210] = new StaticPropertyWatcher("PotionGetExp",{"propertyChange":true},[bindings[314]],null);
         watchers[214] = new StaticPropertyWatcher("GoldTrain",{"propertyChange":true},[bindings[318]],null);
         watchers[34] = new StaticPropertyWatcher("Quality",{"propertyChange":true},[bindings[124],bindings[51],bindings[87],bindings[31]],null);
         watchers[136] = new StaticPropertyWatcher("Skill_B",{"propertyChange":true},[bindings[240]],null);
         watchers[42] = new StaticPropertyWatcher("SailorAttri_B",{"propertyChange":true},[bindings[40],bindings[76]],null);
         watchers[255] = new PropertyWatcher("addZhiStr",{"propertyChange":true},[bindings[360]],propertyGetter);
         watchers[104] = new StaticPropertyWatcher("AddATT5",{"propertyChange":true},[bindings[184]],null);
         watchers[217] = new StaticPropertyWatcher("EveryConsume100_G",{"propertyChange":true},[bindings[321]],null);
         watchers[79] = new StaticPropertyWatcher("OverlordAll",{"propertyChange":true},[bindings[129]],null);
         watchers[265] = new PropertyWatcher("addMinStr",{"propertyChange":true},[bindings[372]],propertyGetter);
         watchers[173] = new StaticPropertyWatcher("AvoidCrit2",{"propertyChange":true},[bindings[278]],null);
         watchers[166] = new StaticPropertyWatcher("MagDef",{"propertyChange":true},[bindings[272]],null);
         watchers[215] = new StaticPropertyWatcher("Gold100GetExp2",{"propertyChange":true},[bindings[319]],null);
         watchers[181] = new StaticPropertyWatcher("BoatUpgCard",{"propertyChange":true},[bindings[286]],null);
         watchers[8] = new StaticPropertyWatcher("Boat",{"propertyChange":true},[bindings[7]],null);
         watchers[134] = new StaticPropertyWatcher("Maintain",{"propertyChange":true},[bindings[235]],null);
         watchers[249] = new PropertyWatcher("liColor",{"propertyChange":true},[bindings[352]],propertyGetter);
         watchers[211] = new StaticPropertyWatcher("QuickTrain2",{"propertyChange":true},[bindings[315]],null);
         watchers[248] = new PropertyWatcher("li",{"propertyChange":true},[bindings[351]],propertyGetter);
         watchers[49] = new StaticPropertyWatcher("None",{"propertyChange":true},[bindings[62],bindings[61]],null);
         watchers[262] = new PropertyWatcher("addTiColor",{"propertyChange":true},[bindings[367]],propertyGetter);
         watchers[207] = new StaticPropertyWatcher("Potion",{"propertyChange":true},[bindings[312]],null);
         watchers[196].updateParent(target);
         watchers[194].updateParent(UILang);
         watchers[190].updateParent(target);
         watchers[184].updateParent(UILang);
         watchers[2].updateParent(UILang);
         watchers[83].updateParent(UILang);
         watchers[55].updateParent(UILang);
         watchers[251].updateParent(target);
         watchers[154].updateParent(UILang);
         watchers[220].updateParent(UILang);
         watchers[4].updateParent(DataManager);
         watchers[4].addChild(watchers[18]);
         watchers[18].addChild(watchers[19]);
         watchers[19].addChild(watchers[20]);
         watchers[4].addChild(watchers[5]);
         watchers[5].addChild(watchers[21]);
         watchers[5].addChild(watchers[13]);
         watchers[5].addChild(watchers[6]);
         watchers[6].addChild(watchers[7]);
         watchers[6].addChild(watchers[9]);
         watchers[6].addChild(watchers[11]);
         watchers[5].addChild(watchers[129]);
         watchers[129].addChild(watchers[180]);
         watchers[129].addChild(watchers[130]);
         watchers[129].addChild(watchers[132]);
         watchers[17].updateParent(UILang);
         watchers[212].updateParent(UILang);
         watchers[258].updateParent(target);
         watchers[164].updateParent(UILang);
         watchers[276].updateParent(UILang);
         watchers[275].updateParent(UILang);
         watchers[256].updateParent(target);
         watchers[156].updateParent(UILang);
         watchers[261].updateParent(target);
         watchers[277].updateParent(UILang);
         watchers[114].updateParent(UILang);
         watchers[77].updateParent(UILang);
         watchers[146].updateParent(UILang);
         watchers[159].updateParent(UILang);
         watchers[170].updateParent(UILang);
         watchers[195].updateParent(target);
         watchers[250].updateParent(target);
         watchers[100].updateParent(UILang);
         watchers[206].updateParent(target);
         watchers[191].updateParent(UILang);
         watchers[177].updateParent(UILang);
         watchers[155].updateParent(UILang);
         watchers[223].updateParent(UILang);
         watchers[178].updateParent(UILang);
         watchers[179].updateParent(UILang);
         watchers[270].updateParent(UILang);
         watchers[199].updateParent(UILang);
         watchers[133].updateParent(UILang);
         watchers[141].updateParent(UILang);
         watchers[259].updateParent(target);
         watchers[278].updateParent(UILang);
         watchers[260].updateParent(target);
         watchers[263].updateParent(target);
         watchers[279].updateParent(UILang);
         watchers[186].updateParent(target);
         watchers[198].updateParent(target);
         watchers[252].updateParent(target);
         watchers[30].updateParent(UILang);
         watchers[1].updateParent(target);
         watchers[185].updateParent(target);
         watchers[152].updateParent(Global);
         watchers[153].parentWatcher = watchers[152];
         watchers[152].addChild(watchers[153]);
         watchers[200].updateParent(UILang);
         watchers[264].updateParent(target);
         watchers[32].updateParent(UILang);
         watchers[274].updateParent(UILang);
         watchers[145].updateParent(UILang);
         watchers[137].updateParent(UILang);
         watchers[219].updateParent(target);
         watchers[219].addChild(watchers[232]);
         watchers[219].addChild(watchers[229]);
         watchers[219].addChild(watchers[230]);
         watchers[219].addChild(watchers[239]);
         watchers[59].updateParent(target);
         watchers[59].addChild(watchers[202]);
         watchers[59].addChild(watchers[60]);
         watchers[60].addChild(watchers[74]);
         watchers[60].addChild(watchers[63]);
         watchers[60].addChild(watchers[70]);
         watchers[60].addChild(watchers[75]);
         watchers[60].addChild(watchers[76]);
         watchers[60].addChild(watchers[72]);
         watchers[60].addChild(watchers[67]);
         watchers[60].addChild(watchers[99]);
         watchers[60].addChild(watchers[97]);
         watchers[60].addChild(watchers[65]);
         watchers[60].addChild(watchers[66]);
         watchers[60].addChild(watchers[62]);
         watchers[60].addChild(watchers[68]);
         watchers[60].addChild(watchers[93]);
         watchers[60].addChild(watchers[87]);
         watchers[60].addChild(watchers[69]);
         watchers[60].addChild(watchers[89]);
         watchers[60].addChild(watchers[71]);
         watchers[60].addChild(watchers[61]);
         watchers[60].addChild(watchers[95]);
         watchers[60].addChild(watchers[85]);
         watchers[60].addChild(watchers[64]);
         watchers[60].addChild(watchers[73]);
         watchers[60].addChild(watchers[91]);
         watchers[59].addChild(watchers[203]);
         watchers[203].addChild(watchers[204]);
         watchers[26].updateParent(UILang);
         watchers[271].updateParent(UILang);
         watchers[12].updateParent(UILang);
         watchers[224].updateParent(UILang);
         watchers[273].updateParent(UILang);
         watchers[205].updateParent(UILang);
         watchers[81].updateParent(UILang);
         watchers[193].updateParent(UILang);
         watchers[58].updateParent(UILang);
         watchers[0].updateParent(UILang);
         watchers[22].updateParent(UILang);
         watchers[162].updateParent(UILang);
         watchers[57].updateParent(UILang);
         watchers[43].updateParent(target);
         watchers[15].updateParent(target);
         watchers[15].addChild(watchers[281]);
         watchers[281].addChild(watchers[282]);
         watchers[15].addChild(watchers[23]);
         watchers[23].addChild(watchers[272]);
         watchers[23].addChild(watchers[127]);
         watchers[23].addChild(watchers[27]);
         watchers[23].addChild(watchers[138]);
         watchers[23].addChild(watchers[109]);
         watchers[23].addChild(watchers[106]);
         watchers[23].addChild(watchers[120]);
         watchers[23].addChild(watchers[118]);
         watchers[23].addChild(watchers[92]);
         watchers[23].addChild(watchers[103]);
         watchers[23].addChild(watchers[112]);
         watchers[23].addChild(watchers[35]);
         watchers[23].addChild(watchers[39]);
         watchers[23].addChild(watchers[90]);
         watchers[23].addChild(watchers[111]);
         watchers[23].addChild(watchers[29]);
         watchers[23].addChild(watchers[80]);
         watchers[23].addChild(watchers[122]);
         watchers[23].addChild(watchers[41]);
         watchers[23].addChild(watchers[33]);
         watchers[23].addChild(watchers[94]);
         watchers[23].addChild(watchers[24]);
         watchers[23].addChild(watchers[102]);
         watchers[23].addChild(watchers[116]);
         watchers[23].addChild(watchers[78]);
         watchers[23].addChild(watchers[86]);
         watchers[23].addChild(watchers[38]);
         watchers[23].addChild(watchers[139]);
         watchers[23].addChild(watchers[84]);
         watchers[23].addChild(watchers[28]);
         watchers[23].addChild(watchers[96]);
         watchers[23].addChild(watchers[46]);
         watchers[46].addChild(watchers[47]);
         watchers[47].addChild(watchers[56]);
         watchers[47].addChild(watchers[51]);
         watchers[47].addChild(watchers[53]);
         watchers[47].addChild(watchers[48]);
         watchers[46].addChild(watchers[50]);
         watchers[23].addChild(watchers[40]);
         watchers[23].addChild(watchers[131]);
         watchers[23].addChild(watchers[115]);
         watchers[23].addChild(watchers[105]);
         watchers[23].addChild(watchers[128]);
         watchers[23].addChild(watchers[125]);
         watchers[23].addChild(watchers[88]);
         watchers[23].addChild(watchers[98]);
         watchers[23].addChild(watchers[108]);
         watchers[23].addChild(watchers[45]);
         watchers[15].addChild(watchers[280]);
         watchers[15].addChild(watchers[142]);
         watchers[142].addChild(watchers[144]);
         watchers[142].addChild(watchers[165]);
         watchers[142].addChild(watchers[169]);
         watchers[142].addChild(watchers[151]);
         watchers[142].addChild(watchers[167]);
         watchers[142].addChild(watchers[143]);
         watchers[142].addChild(watchers[163]);
         watchers[142].addChild(watchers[176]);
         watchers[142].addChild(watchers[174]);
         watchers[142].addChild(watchers[175]);
         watchers[142].addChild(watchers[172]);
         watchers[142].addChild(watchers[171]);
         watchers[142].addChild(watchers[161]);
         watchers[15].addChild(watchers[183]);
         watchers[15].addChild(watchers[150]);
         watchers[15].addChild(watchers[16]);
         watchers[113].updateParent(UILang);
         watchers[267].updateParent(target);
         watchers[37].updateParent(UILang);
         watchers[168].updateParent(UILang);
         watchers[197].updateParent(UILang);
         watchers[147].updateParent(UILang);
         watchers[266].updateParent(target);
         watchers[31].updateParent(UILang);
         watchers[36].updateParent(UILang);
         watchers[44].updateParent(UILang);
         watchers[187].updateParent(UILang);
         watchers[157].updateParent(UILang);
         watchers[222].updateParent(UILang);
         watchers[269].updateParent(UILang);
         watchers[208].updateParent(target);
         watchers[188].updateParent(target);
         watchers[236].updateParent(Math);
         watchers[140].updateParent(UILang);
         watchers[124].updateParent(UILang);
         watchers[10].updateParent(UILang);
         watchers[253].updateParent(target);
         watchers[257].updateParent(target);
         watchers[149].updateParent(UILang);
         watchers[201].updateParent(UILang);
         watchers[231].updateParent(target);
         watchers[213].updateParent(UILang);
         watchers[189].updateParent(UILang);
         watchers[216].updateParent(UILang);
         watchers[135].updateParent(UILang);
         watchers[221].updateParent(UILang);
         watchers[54].updateParent(UILang);
         watchers[126].updateParent(UILang);
         watchers[148].updateParent(UILang);
         watchers[209].updateParent(UILang);
         watchers[158].updateParent(UILang);
         watchers[268].updateParent(target);
         watchers[52].updateParent(UILang);
         watchers[25].updateParent(UILang);
         watchers[101].updateParent(UILang);
         watchers[160].updateParent(UILang);
         watchers[192].updateParent(UILang);
         watchers[82].updateParent(UILang);
         watchers[218].updateParent(target);
         watchers[218].addChild(watchers[240]);
         watchers[218].addChild(watchers[227]);
         watchers[218].addChild(watchers[245]);
         watchers[218].addChild(watchers[241]);
         watchers[218].addChild(watchers[247]);
         watchers[218].addChild(watchers[242]);
         watchers[218].addChild(watchers[246]);
         watchers[218].addChild(watchers[225]);
         watchers[218].addChild(watchers[226]);
         watchers[218].addChild(watchers[244]);
         watchers[218].addChild(watchers[243]);
         watchers[218].addChild(watchers[238]);
         watchers[14].updateParent(UILang);
         watchers[254].updateParent(target);
         watchers[110].updateParent(UILang);
         watchers[107].updateParent(UILang);
         watchers[3].updateParent(UILang);
         watchers[210].updateParent(UILang);
         watchers[214].updateParent(UILang);
         watchers[34].updateParent(UILang);
         watchers[136].updateParent(UILang);
         watchers[42].updateParent(UILang);
         watchers[255].updateParent(target);
         watchers[104].updateParent(UILang);
         watchers[217].updateParent(UILang);
         watchers[79].updateParent(UILang);
         watchers[265].updateParent(target);
         watchers[173].updateParent(UILang);
         watchers[166].updateParent(UILang);
         watchers[215].updateParent(UILang);
         watchers[181].updateParent(UILang);
         watchers[8].updateParent(UILang);
         watchers[134].updateParent(UILang);
         watchers[249].updateParent(target);
         watchers[211].updateParent(UILang);
         watchers[248].updateParent(target);
         watchers[49].updateParent(UILang);
         watchers[262].updateParent(target);
         watchers[207].updateParent(UILang);
      }
   }
}

